apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-node-app:latest # Replace with your ECR repo
          ports:
            - containerPort: 3000
